package_update: true
package_upgrade: false
package_reboot_if_required: true

# packages:
#   - git
#   - curl
#   - vim

users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [adm, cdrom, sudo, dip, lxd, microk8s]
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIB2QVXgFtnegwHXVnxNfGL2+mQBImraGTbCKxihXRLHw vmuser

# runcmd:
#   - snap install microk8s --classic
#   - microk8s status --wait-ready
#   - microk8s enable dns hostpath-storage
#   - microk8s add-node | tee /home/ubuntu/join-node

# final_message: "The system is finally up, after $UPTIME seconds"
