# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { hostname: "k8s-master", ip: "192.168.56.10", memory: 2048, cpus: 2 },
  { hostname: "k8s-node-1", ip: "192.168.56.20", memory: 2048, cpus: 2 },
  { hostname: "k8s-node-2", ip: "192.168.56.30", memory: 2048, cpus: 2 }
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box     = "generic/ubuntu2204"
      node_config.vm.network "private_network", ip: node[:ip]
      node_config.vm.hostname  = node[:hostname]

      node_config.vm.provider "virtualbox" do |vb|
        vb.gui    = false
        vb.name   = node[:hostname]
        vb.memory = node[:memory]
        vb.cpus   = node[:cpus]
      end

      node_config.ssh.insert_key       = false
      node_config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
      
      node_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"

    end
  end
  
  # config.vm.box     = "generic/ubuntu2204"
  # config.vm.network "private_network", ip: "192.168.56.5"


  # config.ssh.insert_key       = false
  # config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
  
  # config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
end
